name: Build Repo RPM
on:
  push:
    branches: [ master]

env: 
    SOURCE_RPM: icinga2-2.13.5-1.fc36.icinga.src.rpm
    MOCK_CONFIG: rocky+epel-9-x86_64
    MOUNT_POINT: /srpm

jobs:
  build-rpm:
    name: Build rpms
    runs-on: ubuntu-22.04

    container:
      image: vgerris/mock-rpmbuilder
      env: 
        SOURCE_RPM: icinga2-2.13.5-1.fc36.icinga.src.rpm
        MOCK_CONFIG: rocky+epel-9-x86_64
        MOUNT_POINT: /srpm

      options: --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged
    defaults:
      run:
        working-directory: ./
    steps:

      - name: Fetch the binaries
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: recursive


