name: Build Repo RPM
on:
  push:
    branches: [ master]

env: 
    SOURCE_RPM: icinga2-2.13.5-1.fc36.icinga.src.rpm
    MOCK_CONFIG: rocky+epel-9-x86_64
    MOUNT_POINT: /srpm

jobs:
  build-rpm:
    name: Build rpms
    runs-on: ubuntu-22.04

    container:
      image: VGerris/docker-mock-rpmbuilder-icinga2:master

      options: --sysctl net.ipv6.conf.all.disable_ipv6=0
    defaults:
      run:
        working-directory: ./
    steps:

      - name: Fetch the binaries
        uses: actions/download-artifact@v4
        with:
          name: srpms
          path: /srpm
